POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1aCIsImlkIjoiNjQ4NjIyNmZlODNjZjcwZDM5ZmEyOWU2IiwiaWF0IjoxNjg2NjgxODk1fQ.fzMdRE3xVlADaaQbGAo2z1Yym1wvRDHGx6V84QxxJSs

{
  "title": "Huh i am authenticated!",
  "author": "Mr Token",
  "url": "www.token.io",
  "likes": 55
}